/**
 * Render a playbook to a portable Markdown kill-chain document.
 *
 * Pure function of the playbook + the in-memory methodology graph — no
 * network, no React, no store access — so it is trivially testable and reused
 * by the panel's per-playbook export button and the command-palette action.
 *
 * The document is laid out as a numbered kill chain: each step shows its
 * ordinal, the technique title, a metadata line (phase · severity ·
 * difficulty · MITRE ATT&CK id) and the operator's per-step note. A summary
 * header lists the phase coverage and the unique MITRE techniques touched, so
 * the export doubles as an engagement plan and an ATT&CK navigator seed.
 */

import type { Methodology, NodeSummary } from '@/features/methodology/types';

import type { Playbook } from './types';

/** A step joined with its resolved node (or null when the node is missing). */
export interface ResolvedStep {
  uid: string;
  nodeId: string;
  note: string;
  node: NodeSummary | null;
  phaseTitle: string | null;
  phaseOrdinal: number | null;
}

/**
 * Resolve a playbook's steps against the live tree, attaching the matching
 * node summary and its phase context. Steps whose node no longer exists keep
 * `node: null` so callers can render a graceful placeholder rather than crash.
 */
export function resolveSteps(
  playbook: Playbook,
  tree: Methodology,
): ResolvedStep[] {
  const byId = new Map(tree.nodes.map((n) => [n.id, n]));
  const phaseById = new Map(tree.phases.map((p) => [p.id, p]));

  return playbook.steps.map((step) => {
    const node = byId.get(step.nodeId) ?? null;
    const phase = node ? phaseById.get(node.phase_id) : undefined;
    return {
      uid: step.uid,
      nodeId: step.nodeId,
      note: step.note,
      node,
      phaseTitle: phase?.title ?? null,
      phaseOrdinal: phase?.ordinal ?? null,
    };
  });
}

function formatStamp(ms: number): string {
  return new Date(ms).toISOString().slice(0, 16).replace('T', ' ');
}

/** Build a Markdown kill-chain document from one playbook. */
export function buildPlaybookMarkdown(
  playbook: Playbook,
  tree: Methodology,
): string {
  const lines: string[] = [];
  const steps = resolveSteps(playbook, tree);

  lines.push(`# ${playbook.name || 'Untitled playbook'}`);
  lines.push('');
  lines.push(
    `> Kill-chain · ${steps.length} step${steps.length === 1 ? '' : 's'} · updated ${formatStamp(
      playbook.updatedAt,
    )} · methodology v${tree.version}`,
  );
  lines.push('');

  if (playbook.objective.trim() !== '') {
    lines.push('## Objective');
    lines.push('');
    for (const l of playbook.objective.trim().split('\n')) lines.push(l);
    lines.push('');
  }

  // Coverage summary — distinct phases (ordered) and MITRE techniques touched.
  const phaseSet = new Map<number, string>();
  const mitre = new Set<string>();
  for (const s of steps) {
    if (s.node) {
      if (s.phaseOrdinal != null && s.phaseTitle) {
        phaseSet.set(s.phaseOrdinal, s.phaseTitle);
      }
      if (s.node.mitre_attack_id) mitre.add(s.node.mitre_attack_id);
    }
  }
  if (phaseSet.size > 0 || mitre.size > 0) {
    lines.push('## Coverage');
    lines.push('');
    if (phaseSet.size > 0) {
      const ordered = [...phaseSet.entries()]
        .sort((a, b) => a[0] - b[0])
        .map(([ord, title]) => `${String(ord).padStart(2, '0')} ${title}`);
      lines.push(`- **Phases:** ${ordered.join(' → ')}`);
    }
    if (mitre.size > 0) {
      lines.push(`- **MITRE ATT&CK:** ${[...mitre].sort().join(', ')}`);
    }
    lines.push('');
  }

  lines.push('## Kill chain');
  lines.push('');

  if (steps.length === 0) {
    lines.push('_No steps yet — add techniques from the canvas or detail panel._');
    lines.push('');
  } else {
    steps.forEach((s, i) => {
      const n = i + 1;
      if (!s.node) {
        lines.push(`### ${n}. _(missing technique: \`${s.nodeId}\`)_`);
        lines.push('');
        return;
      }
      lines.push(`### ${n}. ${s.node.title}`);
      lines.push('');
      const meta: string[] = [];
      if (s.phaseTitle) {
        meta.push(
          `${s.phaseOrdinal != null ? String(s.phaseOrdinal).padStart(2, '0') + ' ' : ''}${s.phaseTitle}`,
        );
      }
      meta.push(s.node.severity);
      meta.push(s.node.difficulty);
      if (s.node.mitre_attack_id) meta.push(s.node.mitre_attack_id);
      lines.push(`_${meta.join(' · ')}_`);
      lines.push('');
      if (s.node.summary.trim() !== '') {
        lines.push(s.node.summary);
        lines.push('');
      }
      if (s.note.trim() !== '') {
        lines.push('**Operator notes:**');
        lines.push('');
        for (const l of s.note.trim().split('\n')) lines.push(`> ${l}`);
        lines.push('');
      }
    });
  }

  lines.push('---');
  lines.push('_Generated by WindowsPE — interactive Windows priv-esc methodology._');
  lines.push('');

  return lines.join('\n');
}
