'use client';

/**
 * Export the user's progress + notes as a single Markdown document.
 *
 * This is the "study export" power feature: an OSCP candidate works through
 * the tree marking nodes done/skipped and jotting per-node notes, then pulls
 * the whole thing out as a portable `.md` checklist they can drop into their
 * exam report or Obsidian vault. Everything is derived from the React Query
 * tree payload + the persisted Zustand slice; nothing hits the network.
 */

import type { Methodology, ProgressStatus } from './types';

interface ExportInput {
  tree: Methodology;
  progress: Record<string, ProgressStatus>;
  notes: Record<string, string>;
}

const STATUS_MARK: Record<ProgressStatus, string> = {
  done: '[x]',
  skipped: '[~]',
};

export function buildMarkdownReport({ tree, progress, notes }: ExportInput): string {
  const lines: string[] = [];
  const now = new Date();

  lines.push('# WindowsPE — Privilege Escalation Checklist');
  lines.push('');
  lines.push(`> Exported ${now.toISOString().slice(0, 16).replace('T', ' ')} · methodology v${tree.version}`);
  lines.push('');

  // Summary counts.
  let done = 0;
  let skipped = 0;
  for (const s of Object.values(progress)) {
    if (s === 'done') done += 1;
    else if (s === 'skipped') skipped += 1;
  }
  const actionable = tree.nodes.filter(
    (n) => n.kind === 'technique' || n.kind === 'tool',
  ).length;
  lines.push(
    `**Progress:** ${done} done · ${skipped} skipped · ${actionable} actionable techniques · ${Object.keys(notes).length} noted`,
  );
  lines.push('');
  lines.push('Legend: `[x]` done · `[~]` skipped · `[ ]` open');
  lines.push('');

  const phases = [...tree.phases].sort((a, b) => a.ordinal - b.ordinal);
  const byId = new Map(tree.nodes.map((n) => [n.id, n]));

  for (const phase of phases) {
    const phaseNodes = tree.nodes.filter((n) => n.phase_id === phase.id);
    if (phaseNodes.length === 0) continue;

    lines.push(`## ${String(phase.ordinal).padStart(2, '0')} · ${phase.title}`);
    lines.push('');

    for (const node of phaseNodes) {
      const status = progress[node.id];
      const mark = status ? STATUS_MARK[status] : '[ ]';
      const parent = node.parent_id ? byId.get(node.parent_id) : undefined;
      const indent = parent ? '  ' : '';
      const metaParts: string[] = [node.severity, node.difficulty];
      if (node.mitre_attack_id) metaParts.push(node.mitre_attack_id);
      const meta = metaParts.join(' · ');

      lines.push(`${indent}- ${mark} **${node.title}** — _${meta}_`);

      const note = notes[node.id];
      if (note && note.trim() !== '') {
        for (const noteLine of note.trim().split('\n')) {
          lines.push(`${indent}  > ${noteLine}`);
        }
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by WindowsPE — interactive Windows priv-esc methodology._');
  lines.push('');

  return lines.join('\n');
}

/**
 * Export *only* the nodes that have personal notes, formatted as a clean
 * Markdown study document. No progress marks, no empty entries — just the
 * user's written notes grouped by phase.
 */
export function buildNotesMarkdownExport({
  tree,
  notes,
  progress,
}: ExportInput): string {
  const lines: string[] = [];
  const now = new Date();

  lines.push('# WindowsPE — Personal Study Notes');
  lines.push('');
  lines.push(
    `> Exported ${now.toISOString().slice(0, 16).replace('T', ' ')} · methodology v${tree.version}`,
  );
  lines.push('');

  const notedNodeIds = new Set(Object.keys(notes));
  if (notedNodeIds.size === 0) {
    lines.push('_No notes yet. Open any technique and add notes in the side panel._');
    lines.push('');
    lines.push('---');
    lines.push('_Generated by WindowsPE — interactive Windows priv-esc methodology._');
    return lines.join('\n');
  }

  // Summary
  const actionable = tree.nodes.filter(
    (n) => n.kind === 'technique' || n.kind === 'tool',
  ).length;
  let done = 0;
  for (const s of Object.values(progress)) {
    if (s === 'done') done += 1;
  }
  const pct = actionable > 0 ? Math.round((done / actionable) * 100) : 0;
  lines.push(
    `**Notes:** ${notedNodeIds.size} technique${notedNodeIds.size === 1 ? '' : 's'} noted · **Progress:** ${pct}% complete (${done}/${actionable})`,
  );
  lines.push('');

  const phases = [...tree.phases].sort((a, b) => a.ordinal - b.ordinal);

  for (const phase of phases) {
    const phaseNodes = tree.nodes.filter(
      (n) => n.phase_id === phase.id && notedNodeIds.has(n.id),
    );
    if (phaseNodes.length === 0) continue;

    lines.push(`## ${String(phase.ordinal).padStart(2, '0')} · ${phase.title}`);
    lines.push('');

    for (const node of phaseNodes) {
      const note = notes[node.id];
      if (!note || note.trim() === '') continue;

      const status = progress[node.id];
      const statusLabel = status === 'done' ? ' ✓' : status === 'skipped' ? ' ~' : '';
      const metaParts: string[] = [node.severity, node.difficulty];
      if (node.mitre_attack_id) metaParts.push(node.mitre_attack_id);

      lines.push(`### ${node.title}${statusLabel}`);
      lines.push('');
      lines.push(`_${metaParts.join(' · ')}_`);
      lines.push('');
      // Emit the note body, preserving blank lines.
      for (const noteLine of note.trim().split('\n')) {
        lines.push(noteLine);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('_Generated by WindowsPE — interactive Windows priv-esc methodology._');
  lines.push('');

  return lines.join('\n');
}

/** Trigger a client-side download of a text blob. */
export function downloadTextFile(filename: string, text: string): void {
  if (typeof document === 'undefined') return;
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke on the next tick so the click has definitely been processed.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
